# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sample: ['sample.pdf', 'short.pdf']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - uses: actions/cache@v4
      id: pip_cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
                        ${{ runner.os }}-pip-
    - name: Install dependencies
      # if: steps.pip_cache.outputs.cache-hit != 'true'
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install package
      run: |
        python -m pip install -e .
    - name: Install linux dependencies:
      run: |
        sudo apt update && sudo apt install espeak ffmpeg libespeak1
    - name: Run application
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      run: |
        python src/podcaster_kerry/main.py -k "$OPENROUTER_API_KEY" -i sample.pdf -o podcast.mp3
    - uses: actions/upload-artifact@v4
      with:
        name: podcast
        path: podcast.mp3
        if-no-files-found: error
        retention-days: 1
        compression-level: 1